### PR TITLE
Remove functions

### PR DESCRIPTION
**Pull request by karelbilek**
As was discussed, I have removed functions that we don't use. (in total, -9000 lines of code)

It took longer than I anticipated. :( I slightly changed the API to make it simpler and to allow to remove even more code.

I have also added "default" flow export so we don't need to write the flowtype "shim" everywhere

I have changed the tests so they actually work again. However, the tests do not include zcash, so the coverage fails (since the zcash code is not at all covered).

I have changed other Javascript projects to use this slightly changed API. I will make PRs where appropriate. (I have made changes in hd-wallet, trezor-link, trezor.js, mytrezor, I will now make the PRs)

edit: I forgot the mention, I have gone through all usages of all the functions here in Trezor JS libraries and added comments about which function is used where. So it can be perhaps more easily refactored some day :)

### CODE REVIEW

**Comment by karel-3d** [comment]
I have made this PR to zcash branch and not master branch, since master branch is behind

**Comment by karel-3d** [comment]
we can turn on travis on this, but it will fail because of the zcash coverage

**Comment by vladimirvolek** [comment]
nice!

**Comment by karel-3d** [comment]
cool. I will force push this to master

**Pull request merged**
